graylog:
    host: host
    use: false
steam:
  api_key: XXXXXXXXXXXX
mongodb:
  host: mongodb://IP:27017/
  db: db_name
  collection: collection_name
api:
  allowed_tokens: token1, token2, token3, token4
test_case:
  user_cookie: ThisIsAUserCookieString
webhooks:
  discord:
    mm_url: https://discord.com/api/webhooks/A
    public_url: https://discord.com/api/webhooks/A
    rebirth_url: https://discord.com/api/webhooks/A
    mm_use: false