graylog:
    host: host
    use: false
steam:
  api_key: XXXXXXXXXXXX
mongodb:
  host: mongodb://IP:27017/
  db: db_name
  collection: collection_name
api:
  allowed_tokens: token1, token2, token3, token4
test_case:
  user_cookie: ThisIsAUserCookieString